export const projects = [
  {
    title: 'CellarClub',
    description: "CellarClub is a complete and fully functional wine-cellar manager web application where users are able to easily create and maintain a collection from a more than 100K items native database, keeping track of purchase information and storage location. Users can also create memories, write tasting reviews and publish them to the CellarClub community.",
      image: '/images/cellarclub_thumb1.png',
      tags: ['Python', 'Django', 'SQLite', 'Node', 'React'],
    source: 'https://github.com/duckbox72/cellar-club',
    visit: 'http://cellarclub-cli.herokuapp.com',
    youtube: 'https://youtu.be/DlXvMzUhy_k',
    id: 0,
  },
  {
    title: 'Quacker',
    description: "Quacker is a simple yet complete Twitter-like social network web application written in Python and JavaScript. Among it's features, Quacker gives users the hability to compose posts, or even better calling, Quacks! Users can also like and post comments on quacks, follow other users, favorite them and later set feed to all-quacks or favorites-quacks.",
      image: '/images/quacker_thumb.png',
      tags: ['Python', 'Django', 'HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/duckbox72/quacker.git',
    youtube: 'https://youtu.be/kh-5d1Dn8Q0',
    id: 1,
  },
  {
    title: 'Mail',
    description: "Mail is an email client implemented in Python, Django and JavaScript that makes API calls to perform a number of tasks like to sending, receiving, replying and forwarding emails. Mail was implemented following a SPA architeture, using Python and Django at the back-end, vanilla JavaScript in the fornt-end and Sqlite for the database.",
    image: '/images/mail_thumb.png',
    tags: ['Python', 'Django', 'SQLite', 'JavaScript'],
    source: 'https://github.com/duckbox72/mail',
    youtube: 'https://youtu.be/Owj85cbph-U',
    id: 2,
  },
  {
    title: 'Auctions',
    description:"Auctions is an eBay-like e-Commerce auction web application implemented in Python and Django. It allows users to perform a variety of actions. When autenticaded users interested in selling an item are able to easily post, manage and close their listings, while users willing to buy a listed product can place bids, make comments and add listings to a watchlist.",
    image: '/images/commerce_thumb.png',
    tags: ['Python', 'Django', 'SQLite', 'HTML', 'CSS'],
    source: 'https://github.com/duckbox72/auctions',
    youtube: 'https://youtu.be/97cva5HQytA',
    id: 3,
  },
  {
    title: 'WineXP',
    description: "WineXp is a Web Application designed in Python and Flask in the back-end with HTML and CSS in the front-end. It was conceived to help anyone interested in fine wines. Basically the app enables users to search for global wine scores (GWS) and global vintage scores (WineXp Vintage Score) in a simple, easy to use and comprehensive interface.",
      image: '/images/winexp_thumb.png',
      tags: ['Python', 'Flask', 'SQLite', 'HTML', 'CSS'],
    source: 'https://github.com/duckbox72/winexp.git',
    visit: 'http://winexp-cli.herokuapp.com',
    youtube: 'https://youtu.be/jAJx1MTEo84',
    id: 4,
  },
  {
    title: "Traffic AI",
    description: "Traffic is an implementation of a Convolutional Neural Network (CNN) built with TensorFlow Keras Sequential Model. The model classifies road signs based on images. For training and testing the model, the German Traffic Sign Recognition Benchmark (GTSRB) labeled dataset, which contains thousands of images of 43 different kinds of road signs, was used.",
      image: '/images/traffic_thumb.png',
      tags: ['Python', 'TensorFLow', 'Keras'],
    source: 'https://github.com/duckbox72/CS50AI-projects/tree/main/traffic',
    youtube: 'https://youtu.be/dUiGJd24B94',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 'Mar 20', text: 'Started my journey', },
  { year: 'Jun 20', text: 'Finished IBM Data Science'},
  { year: 'Nov 20', text: 'Finished CS50' },
  { year: 'Jun 21', text: 'Awarded Profesional Certificate' },
  { year: 'Oct 21', text: 'Awarded Profesional Certificate'},
];